# montecarlo_executor.py

import numpy as np


def montecarlo(instance):
    """
    Monte Carlo integration executor.

    Parameters
    ----------
    instance : Integral
        Constructed Integral instance.

    Returns
    -------
    dict
        {
            "result": float,
            "error": float,
            "volume": float,
            "mean": float,
            "n": int
        }
    """

    # Samples generated by montecarloSim
    fx = np.asarray(instance.y, dtype=float)

    # Number of simulations
    n = instance.n

    # Compute domain volume
    volume = np.prod([b - a for a, b in instance.bounds])

    # First moment
    mean_f = np.mean(fx)

    # Second moment
    mean_f2 = np.mean(fx**2)

    # Monte Carlo estimator
    result = volume * mean_f

    # Classical Monte Carlo error estimate
    error = volume * np.sqrt((mean_f2 - mean_f**2) / n)

    return {
        "result": float(result),
        "error": float(error),
        "volume": float(volume),
        "mean": float(mean_f),
        "n": int(n),
    }
