name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTEST_ADDOPTS: "--maxfail=1 --disable-warnings -q --color=yes"
  CI: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Run unit tests
      #  run: pytest tests/unit/ -v

      #- name: Run integration tests
      #  run: pytest tests/integration/ -v

      #Tests unitarios se probaron en stage 2, 
      #los de integración se probaron en stage 3, 
      #por lo que no es necesario volver a correrlos en stage 4. 
      #Solo se correrán los tests de estrés

      - name: Run stress tests
      #  run: pytest tests/stress/ -v --tb=long -m "pending"
        run: pytest tests/stress/ -vv -s --tb=long --maxfail=1 --full-trace --log-cli-level=DEBUG -m "pending"
